### ISSUE TITLE
Failed to activate the linter-write-good package

### ISSUE THREAD

**Issue by Ricky89GR** [AtomLinter/linter-write-good#31]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter-write-good](https://github.com/gepoch/linter-write-good) package 0.9.0

### Stack Trace

Failed to activate the linter-write-good package

```
At (0 , (_nuclideDiagnosticsCommon || _load_nuclideDiagnosticsCommon(...)).observeTextEditorEvents) is not a function

TypeError: (0 , (_nuclideDiagnosticsCommon || _load_nuclideDiagnosticsCommon(...)).observeTextEditorEvents) is not a function
  at /packages/nuclide/pkg/nuclide-diagnostics-store/lib/LinterAdapter.js:130:183)
  at createSingleAdapter (/packages/nuclide/pkg/nuclide-diagnostics-store/lib/LinterAdapterFactory.js:28:12)
  at addSingleAdapter (/packages/nuclide/pkg/nuclide-diagnostics-store/lib/LinterAdapterFactory.js:39:19)
  at createAdapters (/packages/nuclide/pkg/nuclide-diagnostics-store/lib/LinterAdapterFactory.js:52:5)
  at Activation.consumeLinterProvider (/packages/nuclide/pkg/nuclide-diagnostics-store/lib/main.js:126:100)
  at /packages/nuclide/pkg/commons-atom/createPackage.js:51:34)
  at Provider.module.exports.Provider.provide (/app.asar/node_modules/service-hub/lib/provider.js:34:52)
  at ServiceHub.module.exports.ServiceHub.provide (/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (/app.asar/src/package.js:396:71)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
  at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
  at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
  at /app.asar/src/buffered-process.js:352:11)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

### Commands

```
  3x -0:45.8.0 core:delete (input.hidden-input)
     -0:18.2.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-chester-atom-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
atom-beautify 0.29.22 
atom-bootstrap4 1.4.0 
atom-dark-fusion-syntax 2.2.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-monokai 0.10.9 
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
chester-atom-syntax 0.1.1 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.3 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.57.3 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-swift 0.5.0 
language-thrift 1.0.2 
linter-write-good 0.9.0 
MagicPython 1.0.9 
materialize-css 0.1.0 
merge-conflicts 1.4.4 
monokai 0.22.0 
nuclide 0.218.0 
nuclide-format-js 0.0.36 
pigments 0.39.1 
set-syntax 0.3.2 
sort-lines 0.14.0 
spacegray-atom-dark-syntax 1.3.2 
tool-bar 1.1.0 
```

**Comment by Arcanemagus** [comment]
This is an issue with `nuclide`, not this package.
