### ISSUE TITLE
Failed to load the linter-write-good package

### ISSUE THREAD

**Issue by cforno12** [AtomLinter/linter-write-good#33]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.10.5
**Thrown From**: [linter-write-good](https://github.com/gepoch/linter-write-good) package 0.9.0

### Stack Trace

Failed to load the linter-write-good package

```
At Cannot find module 'xregexp'

Error: Cannot find module 'xregexp'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-write-good/lib/init.coffee:2:13)
    at /packages/linter-write-good/lib/init.coffee:1:1)
    at /packages/linter-write-good/lib/init.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:565:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:473:25)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:810:34
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atomic-chrome 0.3.2 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.12 
fonts 3.0.3 
highlight-selected 0.13.1 
intentions 1.1.5 
language-latex 1.1.1 
language-lisp 0.2.0 
language-viml 1.1.5 
linter 2.2.0 
linter-clang 4.1.2 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
minimap 4.29.7 
open-recent 5.0.0 
pigments 0.40.2 
```

**Comment by Arcanemagus** [comment]
Try re-installing the package, occasionally `apm` fails to install all dependencies.

**Comment by gepoch** [comment]
So APM is failing intermittently? Is it working consistently for other packages? Sounds like it may be a local issue on your machine, possibly..

**Comment by Arcanemagus** [comment]
@gepoch I see it occasionally in many different packages. My best estimate is around 1 in 20k installs _might_ have an issue, but that's an extremely rough guess.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
